version: "3"
services:
  server:
    image: hospital-management-helm:1.0
    ports:
      - "9091:9091"
    environment:
      - spring.datasource.url=jdbc:mysql://mysql:3306/HOSPITAL?allowPublicKeyRetrieval=true&useSSL=false
    networks:
      - hospital-mysql
    depends_on:
      - mysql
       
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=HOSPITAL
    networks:
      - hospital-mysql

networks:
  hospital-mysql:
